SECTOR_TEMPLATES = {
    "Energy": {
        "revenue_growth":   [0.08, 0.09, 0.10],
        "ebitda_margin":    [0.18, 0.19, 0.20],
        "capex_pct_rev":    0.12,
        "wc_pct_rev":       0.05,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (8, 12),
        "pe_range":         (12, 18),
        "description":      "Capital intensive, commodity-linked revenue",
    },
    "Technology": {
        "revenue_growth":   [0.12, 0.13, 0.14],
        "ebitda_margin":    [0.25, 0.26, 0.27],
        "capex_pct_rev":    0.03,
        "wc_pct_rev":       0.08,
        "tax_rate":         0.25,
        "primary_multiple": "pe",
        "ev_ebitda_range":  (15, 25),
        "pe_range":         (20, 30),
        "description":      "Asset-light, high margin, strong FCF",
    },
    "Consumer Defensive": {
        "revenue_growth":   [0.10, 0.11, 0.12],
        "ebitda_margin":    [0.18, 0.19, 0.20],
        "capex_pct_rev":    0.05,
        "wc_pct_rev":       0.06,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (30, 50),
        "pe_range":         (40, 60),
        "description":      "Stable demand, premium multiples",
    },
    "Consumer Cyclical": {
        "revenue_growth":   [0.12, 0.14, 0.15],
        "ebitda_margin":    [0.10, 0.11, 0.12],
        "capex_pct_rev":    0.06,
        "wc_pct_rev":       0.07,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (20, 35),
        "pe_range":         (30, 50),
        "description":      "Growth-driven, discretionary spend",
    },
    "Industrials": {
        "revenue_growth":   [0.08, 0.09, 0.10],
        "ebitda_margin":    [0.14, 0.15, 0.16],
        "capex_pct_rev":    0.08,
        "wc_pct_rev":       0.10,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (8, 14),
        "pe_range":         (15, 25),
        "description":      "Capex heavy, cyclical margins",
    },
    "Communication Services": {
        "revenue_growth":   [0.10, 0.11, 0.12],
        "ebitda_margin":    [0.30, 0.31, 0.32],
        "capex_pct_rev":    0.15,
        "wc_pct_rev":       0.04,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (8, 14),
        "pe_range":         (15, 22),
        "description":      "High capex, recurring revenue",
    },
    "Financial Services": {
        "revenue_growth":   [0.15, 0.14, 0.13],
        "ebitda_margin":    [0.30, 0.31, 0.32],
        "capex_pct_rev":    0.02,
        "wc_pct_rev":       0.03,
        "tax_rate":         0.25,
        "primary_multiple": "pbv",
        "ev_ebitda_range":  None,
        "pe_range":         (15, 22),
        "description":      "Bank/NBFC — use P/BV as primary",
    },
    "Healthcare": {
        "revenue_growth":   [0.11, 0.12, 0.13],
        "ebitda_margin":    [0.20, 0.21, 0.22],
        "capex_pct_rev":    0.06,
        "wc_pct_rev":       0.12,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (18, 28),
        "pe_range":         (25, 40),
        "description":      "R&D intensive, defensive growth",
    },
    "Unknown": {
        "revenue_growth":   [0.10, 0.10, 0.10],
        "ebitda_margin":    [0.15, 0.15, 0.16],
        "capex_pct_rev":    0.06,
        "wc_pct_rev":       0.07,
        "tax_rate":         0.25,
        "primary_multiple": "ev_ebitda",
        "ev_ebitda_range":  (10, 18),
        "pe_range":         (15, 25),
        "description":      "Default template — verify assumptions",
    },
}

def get_template(sector):
    for key in SECTOR_TEMPLATES:
        if key.lower() in sector.lower():
            return SECTOR_TEMPLATES[key]
    return SECTOR_TEMPLATES["Unknown"]